// Array de frases y autores (puedes agregar tus propias frases aquí).
const frases = [
    { frase: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", autor: "John Lennon" },
    { frase: "El único modo de hacer un gran trabajo es amar lo que haces.", autor: "Steve Jobs" },
    { frase: "No importa lo lento que vayas mientras no te detengas.", autor: "Confucio" },
    { frase: "El éxito es ir de fracaso en fracaso sin perder el entusiasmo.", autor: "Winston Churchill" },
    { frase: "La creatividad es la inteligencia divirtiéndose.", autor: "Albert Einstein" },
    { frase: "La vida es como montar en bicicleta. Para mantener el equilibrio, debes seguir adelante.", autor: "Albert Einstein" },
    { frase: "El único límite para nuestros logros de mañana será nuestras dudas de hoy.", autor: "Franklin D. Roosevelt" },
    { frase: "Nunca eres demasiado viejo para fijarte otra meta o soñar un nuevo sueño.", autor: "C.S. Lewis" },
    { frase: "La única forma de hacer un gran trabajo es amar lo que haces.", autor: "Steve Jobs" },
    { frase: "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.", autor: "Seneca" },
    { frase: "No cuentes los días, haz que los días cuenten.", autor: "Muhammad Ali" },
    { frase: "El camino hacia el éxito y el camino hacia el fracaso son casi exactamente iguales.", autor: "Colin R. Davis" },
    { frase: "Si puedes soñarlo, puedes lograrlo.", autor: "Walt Disney" },
    { frase: "No te preocupes por los fracasos, preocúpate por las posibilidades que pierdes cuando ni siquiera lo intentas.", autor: "Jack Canfield" },
    { frase: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.", autor: "Nelson Mandela" },
    { frase: "La verdadera medida de un hombre no se ve en su momento de comodidad, sino en el de la controversia.", autor: "Martin Luther King Jr." },
    { frase: "El valor no es la ausencia de miedo, sino la decisión de que algo es más importante que el miedo.", autor: "Ambrose Redmoon" },
    { frase: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor: "Robert Collier" },
    { frase: "La paciencia es la clave del éxito.", autor: "Bill Gates" },
    { frase: "El camino hacia cualquier objetivo importante está lleno de desafíos.", autor: "Roger Dawson" },
    { frase: "La vida es un sueño, y los sueños, sueños son.", autor: "Pedro Calderón de la Barca" },
    { frase: "La felicidad no es la ausencia de problemas, sino la habilidad para lidiar con ellos.", autor: "Steve Maraboli" },
    { frase: "El amor no tiene edad, siempre está naciendo.", autor: "Blaise Pascal" },
    { frase: "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud.", autor: "Maya Angelou" },
    { frase: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito.", autor: "Albert Schweitzer" },
    { frase: "La verdadera medida de la amistad no viene dada por lo que recibes, sino por lo que das.", autor: "Eleanor Roosevelt" },
    { frase: "No esperes. El momento nunca será el adecuado.", autor: "Napoleón Hill" },
    { frase: "Cada día es una nueva oportunidad para cambiar tu vida.", autor: "Anónimo" },
    { frase: "La vida es un viaje que debe ser disfrutado, no una carrera que debe ser ganada.", autor: "Anónimo" },
    { frase: "La mejor venganza es un éxito masivo.", autor: "Frank Sinatra" },
    { frase: "La vida es una oportunidad, aprovéchala al máximo.", autor: "Anónimo" },
    { frase: "El conocimiento es el único tesoro que no puedes perder.", autor: "Proverbio Hindú" },
    { frase: "La mejor manera de predecir el futuro es crearlo.", autor: "Peter Drucker" },
    { frase: "No puedes cambiar el viento, pero puedes ajustar tus velas.", autor: "Anónimo" },
    { frase: "La felicidad es una elección, no una consecuencia.", autor: "Ralph Marston" },
    { frase: "Si te caes siete veces, levántate ocho.", autor: "Proverbio Chino" },
    { frase: "El verdadero amor no tiene final feliz, porque simplemente no tiene final.", autor: "Anónimo" },
    { frase: "Nunca es tarde para ser lo que podrías haber sido.", autor: "George Eliot" },
    { frase: "La vida es corta, sonríe mientras todavía tienes dientes.", autor: "Anónimo" },
    { frase: "Esta pagina de frases la cree comiendome un croissant. ¡Asi da gusto!", autor: "Alberto Fuentes" },
    { frase: "La gente no cambia, se comporta bien cuando quieren conseguir algo. Por eso mismo callo y me largo", autor: "Alberto Fuentes" },
    { frase: "RECONOCER es una palabra tan importante que se escribe igual al derecho que al revés.", autor:"Anónimo"},
{ frase: "No son las cosas las que nos perturban, sino nuestras opiniones sobre ellas", autor:"Seneca"},
{ frase: "No pretendas que las cosas ocurran como tú quieres. Desea más bien que se produzcan tal como se producen y serás más feliz", autor:"Seneca"},
{ frase: "Cualquier persona capaz de enojarte se convierte en tu amo", autor:"Seneca"},
{ frase: "Solo el hombre culto es libre", autor:"Seneca"},
{ frase: "Deja de buscar problemas innecesarios, es hora de vivir", autor:"Seneca"},
{ frase: "Si hablan mal de ti y es verdad, corrígete; si es mentira, ríete de ello", autor:"Seneca"},
{ frase: "Tomemos como ejemplo a un músico, quien está relajado cuando está tocando solo pero que frente a una audiencia, es una historia diferente", autor:"Seneca"},
{ frase: "La felicidad no consiste en adquirir y gozar, sino en no desear nada", autor:"Seneca"},
{ frase: "Primero dite a ti mismo lo que serías, y luego haz lo que tienes que hacer", autor:"Seneca"},
{ frase: "La cojera es un obstáculo para el cuerpo, no para la mente", autor:"Seneca"},
];

